### PR TITLE
Menu to rename and delete custom chips

### PR DESCRIPTION
**Pull request by gml16**
Created a menu to rename and delete custom chips.
This PR resolves issue #10 and relates to issue #32.

image

Menu is opened when user right clicks one of their custom chips.
Deleting is only allowed if no other chip depends it.
Renaming is only allowed if it is an unused name.

My implementation can be improved as it reloads the `ChipBarUI` for all chips when renaming or deleting a chip, which means it can take at least a second once the user has >20 custom chips.
Feel free to let me know how I can improve it.

I created a dummy non-interactable "View" button to let the user see and potentially edit one of their previous custom chip, an idea for a future PR (related to issue #24).

Edit:
Windows build for this PR:
[buildx86.zip](https://github.com/SebLague/Digital-Logic-Sim/files/6097680/buildx86.zip)
[buildx64.zip](https://github.com/SebLague/Digital-Logic-Sim/files/6097679/buildx64.zip)

### CODE REVIEW

**Comment by SebLague** [comment]
Thanks for contributing! Will take a closer look and see about potentially merging this in the nearish future, when I have some more time free to work on this project.

**Comment by gml16** [comment]
I love your videos Sebastian, and in particular this project made me appreciate my CS architecture classes that I used to not be super interested in. 
I'd be happy to make any changes to this PR and also contribute to other aspects of the code if you've got some roadmap in mind.
Thanks again for the amazing work that you do.

**Comment by davidkowalk** [comment]
This menu should load the chip-data into the main window.

The chip saves all of the data from the main window anyway.

**Comment by t4ccer** [comment]
Currently menu closes only when clicked on 'done' button. How about make menu also close when click outside of it, or on right click?

**Comment by gml16** [comment]
Hey davidkowalk and t4ccer, thanks for your feedback. I wanted to make sure this was a useful feature aligned with the long term goals of the game before working more on it. Please feel free to copy my PR and make any changes if you'd like.

**Comment by FedorLap2006** [comment]
Any updates?

**Comment by gml16** [comment]
I have received requests to share a build for this PR. @SebLague if you'd rather me not upload it I can take it down. I am on Windows so can only create a build for this OS. Hope this is helpful.

[buildx86.zip](https://github.com/SebLague/Digital-Logic-Sim/files/6097680/buildx86.zip)
[buildx64.zip](https://github.com/SebLague/Digital-Logic-Sim/files/6097679/buildx64.zip)

**Comment by lochyj** [comment]
Yep, in his new video it says he is workingon the project and is just polishing it before he releases it.

**Pull request closed without merging**
