### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by bhargavrpatel**
**Context**
This PR addresses comments in https://github.com/SebLague/Digital-Logic-Sim/issues/22. We explicitly add a note that this is a Unity project, where distributions can be downloaded, and a note about Save files.

**Aside**: We should probably render the save path in the simulation tool itself.

**Demo**
[Demo of how this README renders on Github](https://github.com/bhargavrpatel/Digital-Logic-Sim/blob/main/README.md)

### CODE REVIEW

**Comment by willcatmeow** [comment]
i think this is a very good design

**Comment by bhargavrpatel** [comment]
@SebLague Will you be able to review the proposed changes here?

**Comment by willcatmeow** [comment]
would it be possible to add a download link to the README file so you don't have to go to itch.io to download?

**Comment by bhargavrpatel** [comment]
@willcatmeow Please feel free to fork. I am closing this PR as having been inactive and unable to be reviewed by @SebLague.

**Pull request closed without merging**
