### PR TITLE
Misc features

### PR DESCRIPTION
**Pull request by Turnip1234**
## This is a fork of AOx0's merge of all other pull requests, this just has assorted features that I wanted including:

- EEPROM: you can read binary from a .txt file on your computer
- Keyboard: You can key keyboard input
- Disp8: 8x8 display, with color

### More detail on these chips in the in-game instructions section

I also removed some builtin gates, because I wanted to make them in-game myself.

Feel Free to Download the Installer for this here:
[DOWNLOAD](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBbm9KakE1cVo2czVrTmRkekhqQ2R5SEIxbkRPUEE_ZT1GdmM4YmY/root/content)

### CODE REVIEW

**Comment by Turnip1234** [comment]
also includes at least 4 times more instability

**Comment by Azales94500** [comment]
Hey ! Thanks a lot for all of your work all, but i was wondering, is it possible when you have an input with a 4bit wire, to set its value ? when i click on it, nothing happen, and i would like to set its value to test my 4bit adder

**Comment by StiglCZ** [comment]
Hello where I can get download that actually works?

**Comment by Turnip1234** [comment]
https://github.com/DigitalLogicSimCommunity/Digital-Logic-Sim-CE/releases/tag/v0.38
@StiglCZ @FunkyEgg

**Comment by StiglCZ** [comment]
Thank you bro, i tried to compile it myself but it show up error that some json library was missing

**Pull request closed without merging**
