### PR TITLE
Add 4, 8, and 16 bit bus wires

### PR DESCRIPTION
**Pull request by t4ccer**
This PR implements idea from #13.

### CODE REVIEW

**Comment by SebLague** [comment]
Hey, I don't have time right now to review this, but just wanted to say thanks for contributing! I'll review it and see about potentially merging your changes once I have some time again to spend on this project

**Comment by dobrosketchkun** [comment]
Nice!

**Comment by sk8terkyd** [comment]
sorry for this but how do i download this?

**Comment by kayraucklnc** [comment]
This would be a huge bonus!

**Comment by diguifi** [comment]
I personally don't like the idea of having a lot of premade stuff on the bar by default...
Me, as a beginner, like to have my initial project workspace empty, just with the default "AND" and "NOT" gates implemented. I have no idea what bit decoders are and how they work, and them being there by default just makes my workspace feel "dirty" with a bunch of nonsense chips to me.

Maybe if they were put on some different place, like a toolbox menu would be better...

**Comment by UkrainianBanderasCat** [comment]
Hey, but do I need to connect the bus to not or and?

**Pull request closed without merging**
