### PR TITLE
Feat: Set Group Size

### PR DESCRIPTION
**Pull request by sagitarious12**
This PR adds a button on the left side just above where the input pins are which allows for setting the group size in game. Group sizing was built but it was inaccessible to those that downloaded the game without source code. 

This PR also upgrades the unity editor version.

showing the button location.
Button Location

the form modal popup.
Form Modal

the ability to change the group size in game completed.
Result

### CODE REVIEW

**Comment by okyloky9** [comment]
This is a great addition, especially for if we ever get a mobile port. I tried hacking one together but it's really not good with normal mouse controls and still no zoom function. Thanks for adding to the program!

**Comment by CyberPhoenix90** [comment]
This absolutely needs a cap for the group size. Right now you can put numbers that don't even fit in the UI and then freeze the program if you try to place a group that is way too big

**Comment by sagitarious12** [comment]
@CyberPhoenix90 That is very true. I will update the PR and push it in very soon. Thanks for the QA check!

**Comment by CyberPhoenix90** [comment]
Considering that using +/- to create groups you are limited to 8 I think it's very reasonable to have the same limit here

**Pull request closed without merging**
